# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ClimaApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClimaApp
  pod 'Alamofire', '4.7.3'
  pod 'SDWebImage', '4.4.2'

  target 'ClimaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
